### ISSUE TITLE
the total training time

### ISSUE THREAD

**Issue by Bingo-1996** [Gorilla-Lab-SCUT/SS-Conv#3]
您好，请问SS-Conv在linemod和NOCS数据集上分别需要训练多长时间呢？
我在3090机器上训练Plain24 on NOCS数据集20轮大概需要33小时，不知道这个速度是否正常？
![Uploading Screenshot from 2022-05-16 10-13-19.png…]()

**Comment by Bingo-1996** [comment]
![Screenshot from 2022-05-16 10-13-19](https://user-images.githubusercontent.com/69563953/168509678-2ed89635-8201-439b-b2e0-71228ae019da.png)

**Comment by JiehongLin** [comment]
我没在3090上跑过。如果结果正常，应该就没有问题吧~
