### ISSUE TITLE
isnt it correct to set optimizer and lr_scheduler's "name" to "type" ?

### ISSUE THREAD

**Issue by dedoogong** [Gorilla-Lab-SCUT/SS-Conv#4]
Hi~! I'm trying to start training but I got an simple error "
KeyError: "`cfg` or `default_args` must contain the key 'type', but got {'name': 'Adam', 'lr': 0.01, 'betas': [0.5, 0.999], 'eps': 1e-06, 'params': [{'params': <filter object at 0x7fca95bd3f98>}]}\nNone"

So I changed "name" to "type" of "optimizer" and then I got another error.
KeyError: "`cfg` or `default_args` must contain the key 'type', but got {'name': 'StepLR', 'step_size': 2, 'gamma': 0.5, 'optimizer': Adam (\nParameter Group 0\n    amsgrad: False\n    betas: [0.5, 0.999]\n    eps: 1e-06\n    lr: 0.01\n    weight_decay: 0\n)}\nNone"

So, I again changed "name" to "type" of "lr_scheduler". 

and then it seems no more error but, there is no progress on trainning. just got stuck from scratch. 

2022-05-25 11:38:49,545 - using gpu: 2
2022-05-25 11:38:49,546 - => creating model ...
580 images found.

I used my custom images/depth/ so on which are fit to NOCS format and I already passed running the data_processing.py script. 

Please help me~!

**Comment by JiehongLin** [comment]
The problem may be caused by the version of gorilla-core.

**Comment by JiehongLin** [comment]
You could try `pip install gorilla-core==0.2.5.3`.
